### ISSUE TITLE
can't clone the origin code

### ISSUE THREAD

**Issue by Gakiii** [HuanjieGuo/6.824#1]
when i run `git clone git://g.csail.mit.edu/6.824-golabs-2022 6.824`
I got this
```
Cloning into '6.824'...
fatal: unable to connect to g.csail.mit.edu:
g.csail.mit.edu[0: 128.52.128.187]: errno=Connection refused
```
have you ever seen this problem?

**Comment by HuanjieGuo** [comment]
It is because your local network cannot connect to the MIT server.

You can try as follow:

1. Switch to another network, go to your school, your office or nearby library.
2. Use mobile phone hotspot.
3. Learn how to set the Terminal to connect to a proxy and then run it again.

**Comment by Gakiii** [comment]
> It is because your local network cannot connect to the MIT server.
> 
> You can try as follow:
> 
> 1. Switch to another network, go to your school, your office or nearby library.
> 2. Use mobile phone hotspot.
> 3. Learn how to set the Terminal to connect to a proxy and then run it again.

it works, thank you!
